### ISSUE TITLE
Error Encountered When Using the wister Package

### ISSUE THREAD

**Issue by Ozan-Hancer** [cycurity/wister#1]
Hello,

I encountered an error while trying to use the wister package and I need your assistance. Below are the details of the error:

Error Message:

arduino
Copy code
Traceback (most recent call last):
  File "/root/Documents/Wordlists/wister/wister/wister.py", line 1, in <module>
    import wister.control as control
  File "/root/Documents/Wordlists/wister/wister/wister.py", line 1, in <module>
    import wister.control as control
ModuleNotFoundError: No module named 'wister.control'; 'wister' is not a package
Error Description:
I installed the wister package and when I tried to run the wister.py file, I received the above error message. It indicates that the wister.control module cannot be found by the Python module system.

Steps Taken:

Installed the wister package using pip: pip install wister
Ran the wister.py file: python3 wister.py
Received the error message mentioned above.
Additional Information:

Python Version: 3.11
Operating System: Kali
I am seeking your assistance on how to resolve this issue. Please provide guidance on how I can address this problem.

**Comment by nu11pointer** [comment]
Hi. Thanks for reaching out. 

When installing through `pip`, you should run wister just by calling by its name: 
`$ wister`
instead of running the python file. Don't run `$ python3 wister.py` directly.
